name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out the code from GitHub
    - uses: actions/checkout@v3

    # 2. Set up Python 3.9 (Clean environment!)
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # 3. Install your project dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest httpx  # Install test tools

    # 4. Generate Data (Since we didn't push DVC data to a cloud bucket yet)
    - name: Run Data Ingestion
      run: python src/data_loader.py

    # 5. Train Model (To ensure api has a model to load)
    - name: Train Model
      run: python src/train.py

    # 6. Run Tests
    - name: Run Tests
      run: python -m pytest